import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import BottomNav from "@/components/BottomNav";
// OrbitChat is loaded dynamically only when the user opens it
import dynamic from 'next/dynamic';
import PagePerformanceMonitor from '@/components/PagePerformanceMonitor';
import OrbitChatToggle from '@/components/OrbitChatToggle';
import { AuthProvider } from "@/context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col bg-background text-foreground pb-16 md:pb-0`}
      >
        <AuthProvider>
          <Navbar />
          {/* Global performance monitor (client-only) */}
          <PagePerformanceMonitor />
          <main className="flex-1">
            {children}
          </main>
          <Footer />
          <BottomNav />
          {/* OrbitChat is loaded dynamically via OrbitChatToggle to avoid shipping heavy JS to all pages */}
          <OrbitChatToggle />
        </AuthProvider>
      </body>
    </html>
  );
}
