
import fs from 'fs';
import path from 'path';

export default async function handler(req, res) {
  try {
    const { cityCode } = req.query || {};
    // Read local dataset (generated by scripts/generate_data.js)
    const dataPath = path.join(process.cwd(), 'data', 'hotels.json');
    if (!fs.existsSync(dataPath)) {
      return res.status(404).json({ error: 'hotels dataset not found' });
    }
    const items = JSON.parse(fs.readFileSync(dataPath, 'utf8'));

    let filtered = items;
    if (cityCode && String(cityCode).trim().length > 0) {
      const code = String(cityCode).toUpperCase();
      filtered = items.filter(h => (h.nearestAirport && String(h.nearestAirport).toUpperCase() === code) || (h.city && String(h.city).toUpperCase() === code));
    }

    return res.status(200).json({ cityCode: cityCode ? String(cityCode).toUpperCase() : null, count: filtered.length, data: filtered.slice(0, 500) });
  } catch (err) {
    console.error('Hotels API error', err);
    return res.status(500).json({ error: err.message || 'Internal Server Error' });
  }
}
